<?php

########################################################################
# Extension Manager/Repository config file for ext: "extbase_staticinfotables"
#
# Auto generated by Extension Builder 2011-07-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Extbase Static Info Tables',
	'description' => 'Extbase domain models for the static info tables',
	'category' => 'misc',
	'author' => 'Marco Huber',
	'author_email' => 'mail@marco-huber.de',
	'author_company' => '',
	'shy' => '',
	'dependencies' => 'cms,extbase,static_info_tables',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'static_info_tables' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>